services:

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}

    ports:
      - "3306:3306"
    networks:
      - tfc-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: tfc-backend:${BACKEND_VERSION:-latest}
    build:
      context: "."
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      HOST: db
      PORT: ${PORT}
      DATABASE: ${DATABASE}
      DB_USER: ${USERNAME}
      PASSWORD: ${PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT:-3000}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    networks:
      - tfc-network
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:

networks:
  tfc-network:
    driver: bridge