###                  USERS MODULE                       ###

### Créer user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "haroun2e@xyz.com",
    "password": "abc123",
    "nomComplet": "Haroune Belhachani",
    "omnivoxDA": "6304455",
    "omnivoxPassword": "ryad2007",
    "calendrierId": 1
}

### Login 
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "haroun2e@xyz.com",
    "password": "abc123"
}

### Who Am I (Requires valid cookie session)
GET http://localhost:3000/users/whoami

### Logout
POST http://localhost:3000/auth/signout

### GET ONE User BY ID
GET http://localhost:3000/users/1

GET http://localhost:3000/users

### Update User par ID
PATCH http://localhost:3000/users/1
content-type: application/json

{
    "email": "email_updated@xyz.com",
    "nomComplet": "Updated Name"
}

###trouver tous les users
GET  http://localhost:3005/users/getAll
=======
### Delete User par ID
DELETE http://localhost:3000/users/27

### get cours
GET http://localhost:3000/Omnivox/cours


### get cours straight from api
POST http://localhost:8000/classes
Content-Type: application/json

{
  "da": "6304455",
  "password": "ryad2007"
}


### import cours
POST http://localhost:3000/Omnivox/import
