### crée une invitation
POST http://localhost:3000/invitation
content-type: application/json

{
  "type": "AMI",
  "senderId": 1,
  "invitedUserId": 2,
  "amiId": -1
}
### Get toutes les invitations
GET http://localhost:3000/invitation

### mes invitations reçues
GET http://localhost:3000/invitation/received/13


### mes invitations envoyées
GET http://localhost:3000/invitation/sent/13
### Get une invitation
GET http://localhost:3000/invitation/1


PATCH http://localhost:3000/invitation/6/accept

### refuser une  invitation
PATCH http://localhost:3000/invitation/1/refuse

### supprimer une invitation
DELETE http://localhost:3000/invitation/6