###créer user
POST http://localhost:3000/users/signup
content-type: application/json

{
    "email" : "nouveau@xyz.com",
    "password" : "abc123"
}

###login 
POST http://localhost:3000/users/signin
content-type: application/json

{
    "email" : "nouveau@xyz.com",
    "password" : "abc123"
}

### Who Am I
GET http://localhost:3000/users/whoami

### Logout
POST http://localhost:3000/users/signout

### GET ONE BY ID
GET http://localhost:3000/users/1

### GET ALL USers
GET http://localhost:3000/users/

###update 
PATCH http://localhost:3000/users/1
content-type: application/json

{
    "email" : "email@xyz.com",
    "password" : "abc123"
}

### Delete User par ID
DELETE http://localhost:3000/users/20